config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # resources :categories
  # resources :deals
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "categories#index"
  resources :users
  resources :categories, only: [:index, :show, :new, :create, :destroy] do
    resources :deals, only: [:index, :show, :new, :create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :deals, dependent: :destroy
  belongs_to :author, class_name: 'User', foreign_key: :author_id

  validates :name, length: { minimum: 1 }
  validates :icon, presence: true
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: '::User', foreign_key: :author_id
  belongs_to :category

  validates :name, length: { minimum: 1 }
  validates :amount, numericality: { only_integer: true, greater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :name, length: { minimum: 1 }

  has_many :categories, dependent: :destroy
  has_many :deals, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password])
  end
end

app/controllers/categories_controller.rb
require 'base64'

class CategoriesController < ApplicationController
  before_action :set_category, only: %i[show edit update destroy]

  # GET /categories or /categories.json
  def index
    redirect_to new_user_session_path if user_signed_in? == false
    @categories = Category.where(author_id: current_user.id)
  end

  # GET /categories/1 or /categories/1.json
  def show
    @category = Category.find(params[:id])
    @deals = Deal.where(category_id: params[:id])
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit; end

  # POST /categories or /categories.json
  def create
    file_content = File.read(category_params['icon'].tempfile, &:read)
    encoded_string = Base64.strict_encode64(file_content)
    @category = Category.create(author: current_user, name: category_params['name'], icon: encoded_string)

    respond_to do |format|
      if @category.save
        format.html do
          redirect_to categories_path, notice: 'Category was successfully created.'
        end
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to category_url(@category), notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_category
    @category = Category.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]

  # GET /deals or /deals.json
  def index
    @deals = Deal.where(category_id: params[:category_id]).order(created_at: :desc)
    @category = Category.find(params[:category_id])
  end

  # GET /deals/1 or /deals/1.json
  def show; end

  # GET /deals/new
  def new
    @deal = Deal.new
    @category = Category.find(params[:category_id])
    p @category
  end

  # GET /deals/1/edit
  def edit; end

  # POST /deals or /deals.json
  def create
    @user = current_user
    @category = Category.find(params[:category_id])
    @deal = Deal.create(author: current_user, category_id: @category.id, name: deal_params['name'],
                        amount: deal_params['amount'])

    respond_to do |format|
      if @deal.save
        format.html { redirect_to category_deals_path(@category) }
        format.json { render :show, status: :created, location: @deal }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deals/1 or /deals/1.json
  def update
    respond_to do |format|
      if @deal.update(deal_params)
        format.html { redirect_to deal_url(@deal), notice: 'Deal was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deals/1 or /deals/1.json
  def destroy
    @deal.destroy

    respond_to do |format|
      format.html { redirect_to category_deals_path, notice: 'Deal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:name, :amount)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # before_action :set_user, only: %i[show edit update destroy]

  # GET /users or /users.json
  def index
    redirect_to new_user_session_path if user_signed_in? == false
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>" class="category-item-left">
  <div class="cat-img-ctn">
      <%= image_tag "data:image/png;base64,#{category.icon}", :class => "category-img" %>
  </div>
  <div class="category-det">
    <h5 class="cat-det"><%= category.name %></h5>
    <h5 class="cat-det date">$ <%= category.deals.map{|deal| deal.amount }.sum %></h5>
  </div>

</div>

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.text_field :name, autofocus: true, placeholder: 'Name', required: true%>
  </div>

  <div class="field">
    <%= form.file_field :icon, autofocus: true, placeholder: 'Icon', required: true %>
  </div>

  <div class="button-link">
    <%= form.submit "Valider", class: 'but-default' %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render "form", category: @category %>

<br>

<div>
  <%= link_to "Show this category", @category %> |
  <%= link_to "Back to categories", categories_path %>
</div>

app/views/categories/index.html.erb
<div class="category-ctn">
  <div class="category-nav">
    <div class="nav-title-ctn">
      <h3 class="nav-title">Categories</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <div>

  </div>
  <div id="categories" class="category-list-ctn">
    <% if @categories.count != 0 %>
    <% @categories.each do |category| %>
      <%= link_to category_deals_path(category.id) do %>
      <div class="category-item">
        <%= render category %>
        <div class="category-item-right">
          <%= button_to 'Details', category_path(category), method: :delete, class: "btn-rmv"%>
        </div>
      </div>
      <% end %>
    <% end %>
      <%end %>
  </div>

  <div class="bottom-button">
    <%= link_to "New category", new_category_path, class: 'but-default bottom-btn'%>
  </div>
</div>

app/views/categories/new.html.erb
<div class="cate-create-ctn">
  <div class="category-nav">
    <%= link_to categories_path do %>
      <h2><</h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">New category</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <%= render "form", category: @category %>

</div>

app/views/categories/show.html.erb
<p style="color: green"><%= notice %></p>

<div>
  <div>
    <h5>Total amount : </h5>
    <h5><%= @deals.inject(0, :+) %></h5>
  </div>
  <% @deals.each do |deal| %>
    <p><%= deal.name %></p>
    <p><%= deal.amount %></p>
    <p><%= deal.id %></p>
  <% end %>
</div>

<div>

  <div>
    <%= link_to "Add new transaction", new_category_deal_path(@category) %>
  </div>
  <%= link_to "Back to categories", :back %>

  <%#= button_to "Destroy this category", @category, method: :delete %>
</div>

app/views/deals/_deal.html.erb
<div id="<%= dom_id deal %>" class="category-item">
  <div class="category-det">
    <h4 class="cat-det">Deal N* <%= deal.id.to_s.rjust(5, "0") %></h4>
    <h4 class="cat-det"> Name : <%= deal.name %></h4>
  </div>
  <div class="category-item-right">
    <h4 class="cat-det">$ <%= deal.amount %></h4>
  </div>
</div>

app/views/deals/index.html.erb
<div class="category-ctn">
  <div class="category-nav">
    <%= link_to categories_path do %>
      <h2><</h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">Deals</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>
  <div class="price-band">
    <h5>Total amount : </h5>
    <h5>$ <%= @deals.map { |deal| deal.amount }.sum %></h5>
  </div>

  <div id="deals">
    <% @deals.each do |deal| %>
      <%= render deal %>
      <%#= button_to "Remove", category_deal_path(@category, deal), method: :delete %>
    <% end %>
  </div>

  <div class="bottom-button">
    <%= link_to "New deal", new_category_deal_path, class: 'but-default bottom-btn' %>
  </div>
</div>

app/views/deals/new.html.erb
<div class="cate-create-ctn">
  <div class="category-nav">
    <%= link_to category_deals_path do %>
      <h2><</h2>
    <% end %>
    <div class="nav-title-ctn">
      <h3 class="nav-title">New Deal</h3>
    </div>
    <div class="nav-title-ctn">
      <%= link_to "Log out", destroy_user_session_path, 'data-turbo-method': :delete, class: 'but-default log-out' %>
    </div>
  </div>

  <%= form_with model: @deal, url: category_deals_path, method: :post, class: 'form' do |form| %>
    <% if @deal.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h2>

        <ul>
          <% @deal.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.text_field :name, autofocus: true, placeholder: "Name", required: true %>
    </div>

    <div class="field">
      <%= form.number_field :amount, autofocus: true, placeholder: "Amount", required: true %>
    </div>

    <div class="button-link">
      <%= form.submit "Valider", class: 'but-default' %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.erb
<% if user_signed_in? %>
  <nav>
    <p>This is the navigation</p>
  </nav>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TransacCenter</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
<%#= render 'layouts/navbar' %>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
    </p>
  <% end %>
</div>